[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
amoy = "${AMOY_RPC_URL}"
arbitrum-sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
optimism-sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
arbitrum_one = { key = "${ARBISCAN_API_KEY}" }
optimistic_ethereum = { key = "${OPTIMISTIC_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
